<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class LanguageSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('ab', 'Abkhazian')");
        DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('ace', 'Achinese')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('ach', 'Acoli')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('ada', 'Adangme')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('ady', 'Adyghe')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('aa', 'Afar')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('afh', 'Afrihili')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('af', 'Afrikaans')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('agq', 'Aghem')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('ain', 'Ainu')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('ak', 'Akan')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('akk', 'Akkadian')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('bss', 'Akoose')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('akz', 'Alabama')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('sq', 'Albanian')");
        DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('ale', 'Aleut')");
        DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('arq', 'Algerian Arabic')");
        DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('am', 'Amarik')");
        DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('en_US', 'American English')");
        DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('en', 'English')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('ase', 'American Sign Language')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('egy', 'Ancient Egyptian')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('grc', 'Ancient Greek')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('anp', 'Angika')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('njo', 'Ao Naga')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('ar', 'Arabik')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('an', 'Aragonese')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('arc', 'Aramaic')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('aro', 'Araona')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('arp', 'Arapaho')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('arw', 'Ainsertak')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('hy', 'Armenian')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('rup', 'Aromanian')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('frp', 'Arpitan')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('as', 'Assamese')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('ast', 'Asturian')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('asa', 'Asu')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('cch', 'Atsam')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('en_AU', 'Australian English')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('de_AT', 'Austrian German')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('av', 'Avaric')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('ae', 'Avestan')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('awa', 'Awadhi')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('ay', 'Aymara')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('az', 'Azerbaijani')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('bfq', 'Badaga')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('ksf', 'Bafia')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('bfd', 'Bafut')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('bqi', 'Bakhtiari')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('ban', 'Balinese')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('bal', 'Baluchi')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('bm', 'Bambara')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('bax', 'Bamun')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('bjn', 'Banjar')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('bas', 'Basaa')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('ba', 'Bashkir')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('eu', 'Basque')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('bbc', 'Batak Toba')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('bar', 'Bavarian')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('bej', 'Beja')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('be', 'Belarus kasa')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('bem', 'Bemba')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('bez', 'Bena')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('bn', 'Bengali kasa')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('bew', 'Betawi')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('my', 'Bɛɛmis kasa')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('bho', 'Bhojpuri')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('bik', 'Bikol')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('bin', 'Bini')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('bpy', 'Bishnupriya')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('bi', 'Bislama')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('byn', 'Blin')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('zbl', 'Blissymbols')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('brx', 'Bodo')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('en', 'Borɔfo')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('bs', 'Bosnian')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('bg', 'Bɔlgeria kasa')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('brh', 'Brahui')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('bra', 'Braj')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('pt_BR', 'Brazilian Portuguese')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('br', 'Breton')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('en_GB', 'British English')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('bug', 'Buginese')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('bum', 'Bulu')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('bua', 'Buriat')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('cad', 'Caddo')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('frc', 'Cajun French')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('en_CA', 'Canadian English')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('fr_CA', 'Canadian French')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('yue', 'Cantonese')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('cps', 'Capiznon')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('car', 'Carib')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('ca', 'Catalan')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('cay', 'Cayuga')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('ceb', 'Cebuano')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('tzm', 'Central Atlas Tamazight')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('dtp', 'Central Dusun')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('ckb', 'Central Kurdish')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('esu', 'Central Yupik')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('shu', 'Chadian Arabic')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('chg', 'Chagatai')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('ch', 'Chamorro')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('ce', 'Chechen')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('chr', 'Cherokee')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('chy', 'Cheyenne')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('chb', 'Chibcha')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('cgg', 'Chiga')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('qug', 'Chimborazo Highland Quichua')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('chn', 'Chinook Jargon')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('chp', 'Chipewyan')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('cho', 'Choctaw')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('cu', 'Church Slavic')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('chk', 'Chuukese')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('cv', 'Chuvash')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('nwc', 'Classical Newari')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('syc', 'Classical Syriac')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('ksh', 'Colognian')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('swb', 'Comorian')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('swc', 'Congo Swahili')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('cop', 'Coptic')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('kw', 'Cornish')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('co', 'Corsican')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('cr', 'Cree')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('mus', 'Creek')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('crh', 'Crimean Turkish')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('hr', 'Croatian')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('dak', 'Dakota')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('da', 'Danish')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('dar', 'Dargwa')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('dzg', 'Dazaga')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('del', 'Delaware')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('nl', 'Dɛɛkye')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('din', 'Dinka')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('dv', 'Divehi')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('doi', 'Dogri')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('dgr', 'Dogrib')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('dua', 'Duala')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('dyu', 'Dyula')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('dz', 'Dzongkha')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('frs', 'Eastern Frisian')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('efi', 'Efik')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('arz', 'Egyptian Arabic')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('eka', 'Ekajuk')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('elx', 'Elamite')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('ebu', 'Embu')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('egl', 'Emilian')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('myv', 'Erzya')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('eo', 'Esperanto')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('et', 'Estonian')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('pt_PT', 'European Portuguese')");
        DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('es_ES', 'European Spanish')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('ee', 'Ewe')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('ewo', 'Ewondo')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('ext', 'Extremaduran')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('fan', 'Fang')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('fat', 'Fanti')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('fo', 'Faroese')");
        DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('hif', 'Fiji Hindi')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('fj', 'Fijian')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('fil', 'Filipino')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('fi', 'Finnish')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('nl_BE', 'Flemish')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('fon', 'Fon')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('gur', 'Frafra')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('fr', 'Frɛnkye')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('fur', 'Friulian')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('ff', 'Fulah')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('gaa', 'Ga')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('gag', 'Gagauz')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('gl', 'Galician')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('gan', 'Gan Chinese')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('lg', 'Ganda')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('gay', 'Gayo')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('gba', 'Gbaya')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('gez', 'Geez')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('ka', 'Georgian')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('aln', 'Gheg Albanian')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('bbj', 'Ghomala')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('glk', 'Gilaki')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('gil', 'Gilbertese')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('gom', 'Goan Konkani')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('gon', 'Gondi')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('gor', 'Gorontalo')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('got', 'Gothic')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('grb', 'Grebo')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('el', 'Greek kasa')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('gn', 'Guarani')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('gu', 'Gujarati')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('guz', 'Gusii')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('gwi', 'Gwichʼin')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('de', 'Gyaaman')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('jv', 'Gyabanis kasa')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('ja', 'Gyapan kasa')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('hai', 'Haida')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('ht', 'Haitian')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('hak', 'Hakka Chinese')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('hu', 'Hangri kasa')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('ha', 'Hausa')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('haw', 'Hawaiian')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('he', 'Hebrew')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('hz', 'Herero')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('hil', 'Hiligaynon')");
        DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('hi', 'Hindi')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('ho', 'Hiri Motu')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('hit', 'Hittite')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('hmn', 'Hmong')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('hup', 'Hupa')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('iba', 'Iban')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('ibb', 'Ibibio')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('is', 'Icelandic')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('io', 'Ido')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('ig', 'Igbo')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('ilo', 'Iloko')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('smn', 'Inari Sami')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('id', 'Indonihyia kasa')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('izh', 'Ingrian')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('inh', 'Ingush')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('ia', 'Interlingua')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('ie', 'Interlingue')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('iu', 'Inuktitut')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('ik', 'Inupiaq')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('ga', 'Irish')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('it', 'Italy kasa')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('jam', 'Jamaican Creole English')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('kaj', 'Jju')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('dyo', 'Jola-Fonyi')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('jrb', 'Judeo-Arabic')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('jpr', 'Judeo-Persian')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('jut', 'Jutish')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('kbd', 'Kabardian')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('kea', 'Kabuverdianu')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('kab', 'Kabyle')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('kac', 'Kachin')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('kgp', 'Kaingang')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('kkj', 'Kako')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('kl', 'Kalaallisut')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('kln', 'Kalenjin')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('xal', 'Kalmyk')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('kam', 'Kamba')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('km', 'Kambodia kasa')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('kbl', 'Kanembu')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('kn', 'Kannada')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('kr', 'Kanuri')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('kaa', 'Kara-Kalpak')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('krc', 'Karachay-Balkar')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('krl', 'Karelian')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('ks', 'Kashmiri')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('csb', 'Kashubian')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('kaw', 'Kawi')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('kk', 'Kazakh')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('ken', 'Kenyang')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('kha', 'Khasi')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('kho', 'Khotanese')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('khw', 'Khowar')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('ki', 'Kikuyu')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('kmb', 'Kimbundu')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('krj', 'Kinaray-a')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('kiu', 'Kirmanjki')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('tlh', 'Klingon')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('bkm', 'Kom')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('kv', 'Komi')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('koi', 'Komi-Permyak')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('kg', 'Kongo')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('kok', 'Konkani')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('ko', 'Korea kasa')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('kfo', 'Koro')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('kos', 'Kosraean')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('avk', 'Kotava')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('khq', 'Koyra Chiini')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('ses', 'Koyraboro Senni')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('kpe', 'Kpelle')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('kri', 'Krio')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('kj', 'Kuanyama')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('kum', 'Kumyk')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('ku', 'Kurdish')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('kru', 'Kurukh')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('kut', 'Kutenai')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('nmg', 'Kwasio')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('zh', 'Kyaena kasa')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('cs', 'Kyɛk kasa')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('ky', 'Kyrgyz')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('quc', 'Kʼicheʼ')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('lad', 'Ladino')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('lah', 'Lahnda')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('lkt', 'Lakota')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('lam', 'Lamba')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('lag', 'Langi')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('lo', 'Lao')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('ltg', 'Latgalian')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('la', 'Latin')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('es_419', 'Latin American Spanish')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('lv', 'Latvian')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('lzz', 'Laz')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('lez', 'Lezghian')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('lij', 'Ligurian')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('li', 'Limburgish')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('ln', 'Lingala')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('lfn', 'Lingua Franca Nova')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('lzh', 'Literary Chinese')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('lt', 'Lithuanian')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('liv', 'Livonian')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('jbo', 'Lojban')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('lmo', 'Lombard')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('nds', 'Low German')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('sli', 'Lower Silesian')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('dsb', 'Lower Sorbian')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('loz', 'Lozi')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('lu', 'Luba-Katanga')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('lua', 'Luba-Lulua')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('lui', 'Luiseno')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('smj', 'Lule Sami')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('lun', 'Lunda')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('luo', 'Luo')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('lb', 'Luxembourgish')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('luy', 'Luyia')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('mde', 'Maba')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('mk', 'Macedonian')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('jmc', 'Machame')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('mad', 'Madurese')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('maf', 'Mafa')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('mag', 'Magahi')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('vmf', 'Main-Franconian')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('mai', 'Maithili')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('mak', 'Makasar')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('mgh', 'Makhuwa-Meetto')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('kde', 'Makonde')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('mg', 'Malagasy')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('ms', 'Malay kasa')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('ml', 'Malayalam')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('mt', 'Maltese')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('mnc', 'Manchu')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('mdr', 'Mandar')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('man', 'Mandingo')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('mni', 'Manipuri')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('gv', 'Manx')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('mi', 'Maori')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('arn', 'Mapuche')");
        DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('mr', 'Marathi')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('chm', 'Mari')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('mh', 'Marshallese')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('mwr', 'Marwari')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('mas', 'Masai')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('mzn', 'Mazanderani')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('byv', 'Medumba')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('men', 'Mende')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('mwv', 'Mentawai')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('mer', 'Meru')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('mgo', 'Metaʼ')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('es_MX', 'Mexican Spanish')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('mic', 'Micmac')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('dum', 'Middle Dutch')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('enm', 'Middle English')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('frm', 'Middle French')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('gmh', 'Middle High German')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('mga', 'Middle Irish')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('nan', 'Min Nan Chinese')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('min', 'Minangkabau')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('xmf', 'Mingrelian')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('mwl', 'Mirandese')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('lus', 'Mizo')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('ar_001', 'Modern Standard Arabic')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('moh', 'Mohawk')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('mdf', 'Moksha')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('ro_MD', 'Moldavian')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('lol', 'Mongo')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('mn', 'Mongolian')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('mfe', 'Morisyen')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('ary', 'Moroccan Arabic')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('mos', 'Mossi')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('mul', 'Multiple Languages')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('mua', 'Mundang')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('ttt', 'Muslim Tat')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('mye', 'Myene')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('naq', 'Nama')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('na', 'Nauru')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('nv', 'Navajo')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('ng', 'Ndonga')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('nap', 'Neapolitan')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('new', 'Newari')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('ne', 'Nɛpal kasa')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('sba', 'Ngambay')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('nnh', 'Ngiemboon')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('jgo', 'Ngomba')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('yrl', 'Nheengatu')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('nia', 'Nias')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('niu', 'Niuean')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('zxx', 'No linguistic content')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('nog', 'Nogai')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('nd', 'North Ndebele')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('frr', 'Northern Frisian')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('se', 'Northern Sami')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('nso', 'Northern Sotho')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('no', 'Norwegian')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('nb', 'Norwegian Bokmål')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('nn', 'Norwegian Nynorsk')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('nov', 'Novial')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('nus', 'Nuer')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('nym', 'Nyamwezi')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('ny', 'Nyanja')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('nyn', 'Nyankole')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('tog', 'Nyasa Tonga')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('nyo', 'Nyoro')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('nzi', 'Nzima')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('nqo', 'NʼKo')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('oc', 'Occitan')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('oj', 'Ojibwa')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('ang', 'Old English')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('fro', 'Old French')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('goh', 'Old High German')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('sga', 'Old Irish')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('non', 'Old Norse')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('peo', 'Old Persian')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('pro', 'Old Provençal')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('or', 'Oriya')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('om', 'Oromo')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('osa', 'Osage')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('os', 'Ossetic')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('ota', 'Ottoman Turkish')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('pal', 'Pahlavi')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('pfl', 'Palatine German')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('pau', 'Palauan')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('pi', 'Pali')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('pam', 'Pampanga')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('pag', 'Pangasinan')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('pap', 'Papiamento')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('ps', 'Pashto')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('pdc', 'Pennsylvania German')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('fa', 'Pɛɛhyia kasa')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('phn', 'Phoenician')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('pcd', 'Picard')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('pms', 'Piedmontese')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('pdt', 'Plautdietsch')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('pon', 'Pohnpeian')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('pnt', 'Pontic')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('pl', 'Pɔland kasa')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('pt', 'Pɔɔtugal kasa')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('prg', 'Prussian')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('pa', 'Pungyabi kasa')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('qu', 'Quechua')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('ru', 'Rahyia kasa')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('raj', 'Rajasthani')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('rap', 'Rapanui')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('rar', 'Rarotongan')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('rw', 'Rewanda kasa')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('rif', 'Riffian')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('rgn', 'Romagnol')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('rm', 'Romansh')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('rom', 'Romany')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('rof', 'Rombo')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('ro', 'Romenia kasa')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('root', 'Root')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('rtm', 'Rotuman')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('rug', 'Roviana')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('rn', 'Rundi')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('rue', 'Rusyn')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('rwk', 'Rwa')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('ssy', 'Saho')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('sah', 'Sakha')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('sam', 'Samaritan Aramaic')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('saq', 'Samburu')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('sm', 'Samoan')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('sgs', 'Samogitian')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('sad', 'Sandawe')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('sg', 'Sango')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('sbp', 'Sangu')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('sa', 'Sanskrit')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('sat', 'Santali')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('sc', 'Sardinian')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('sas', 'Sasak')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('sdc', 'Sassarese Sardinian')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('stq', 'Saterland Frisian')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('saz', 'Saurashtra')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('sco', 'Scots')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('gd', 'Scottish Gaelic')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('sly', 'Selayar')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('sel', 'Selkup')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('seh', 'Sena')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('see', 'Seneca')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('sr', 'Serbian')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('sh', 'Serbo-Croatian')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('srr', 'Serer')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('sei', 'Seri')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('ksb', 'Shambala')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('shn', 'Shan')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('sn', 'Shona')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('ii', 'Sichuan Yi')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('scn', 'Sicilian')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('sid', 'Sidamo')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('bla', 'Siksika')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('szl', 'Silesian')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('zh_Hans', 'Simplified Chinese')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('sd', 'Sindhi')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('si', 'Sinhala')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('sms', 'Skolt Sami')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('den', 'Slave')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('sk', 'Slovak')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('sl', 'Slovenian')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('xog', 'Soga')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('sog', 'Sogdien')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('so', 'Somalia kasa')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('snk', 'Soninke')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('azb', 'South Azerbaijani')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('nr', 'South Ndebele')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('alt', 'Southern Altai')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('sma', 'Southern Sami')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('st', 'Southern Sotho')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('es', 'Spain kasa')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('srn', 'Sranan Tongo')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('zgh', 'Standard Moroccan Tamazight')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('suk', 'Sukuma')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('sux', 'Sumerian')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('su', 'Sundanese')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('sus', 'Susu')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('sw', 'Swahili')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('ss', 'Swati')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('sv', 'Sweden kasa')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('fr_CH', 'Swiss French')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('gsw', 'Swiss German')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('de_CH', 'Swiss High German')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('syr', 'Syriac')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('shi', 'Tachelhit')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('th', 'Taeland kasa')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('tl', 'Tagalog')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('ty', 'Tahitian')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('dav', 'Taita')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('tg', 'Tajik')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('tly', 'Talysh')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('tmh', 'Tamashek')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('ta', 'Tamil kasa')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('trv', 'Taroko')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('twq', 'Tasawaq')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('tt', 'Tatar')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('te', 'Telugu')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('ter', 'Tereno')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('teo', 'Teso')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('tet', 'Tetum')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('tr', 'Tɛɛki kasa')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('bo', 'Tibetan')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('tig', 'Tigre')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('ti', 'Tigrinya')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('tem', 'Timne')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('tiv', 'Tiv')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('tli', 'Tlingit')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('tpi', 'Tok Pisin')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('tkl', 'Tokelau')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('to', 'Tongan')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('fit', 'Tornedalen Finnish')");
        DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('zh_Hant', 'Traditional Chinese')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('tkr', 'Tsakhur')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('tsd', 'Tsakonian')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('tsi', 'Tsimshian')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('ts', 'Tsonga')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('tn', 'Tswana')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('tcy', 'Tulu')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('tum', 'Tumbuka')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('aeb', 'Tunisian Arabic')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('tk', 'Turkmen')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('tru', 'Turoyo')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('tvl', 'Tuvalu')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('tyv', 'Tuvinian')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('tw', 'Twi')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('kcg', 'Tyap')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('udm', 'Udmurt')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('uga', 'Ugaritic')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('uk', 'Ukren kasa')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('umb', 'Umbundu')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('und', 'Unknown Language')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('hsb', 'Upper Sorbian')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('ur', 'Urdu kasa')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('ug', 'Uyghur')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('uz', 'Uzbek')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('vai', 'Vai')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('ve', 'Venda')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('vec', 'Venetian')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('vep', 'Veps')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('vi', 'Viɛtnam kasa')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('vo', 'Volapük')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('vro', 'Võro')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('vot', 'Votic')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('vun', 'Vunjo')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('wa', 'Walloon')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('wae', 'Walser')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('war', 'Waray')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('wbp', 'Warlpiri')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('was', 'Washo')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('guc', 'Wayuu')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('cy', 'Welsh')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('vls', 'West Flemish')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('fy', 'Western Frisian')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('mrj', 'Western Mari')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('wal', 'Wolaytta')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('wo', 'Wolof')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('wuu', 'Wu Chinese')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('xh', 'Xhosa')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('hsn', 'Xiang Chinese')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('yav', 'Yangben')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('yao', 'Yao')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('yap', 'Yapese')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('ybb', 'Yemba')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('yi', 'Yiddish')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('yo', 'Yoruba')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('zap', 'Zapotec')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('dje', 'Zarma')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('zza', 'Zaza')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('zea', 'Zeelandic')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('zen', 'Zenaga')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('za', 'Zhuang')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('gbz', 'Zoroastrian Dari')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('zu', 'Zulu')");
        // DB::insert("INSERT INTO `languages` (`slug`, `name`) VALUES ('zun', 'Zuni')");
    }
}
